# stage1 - build react app first 
FROM node:14 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/
# COPY ./yarn.lock /app/
RUN npm install
COPY . /app
EXPOSE 3000
CMD ["npm", "start"]